# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_v2/sample_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_v2/sample_action.proto',
  package='drive.common.control_v2',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x63ontrol_v2/sample_action.proto\x12\x17\x64rive.common.control_v2\"#\n\x14\x46uncParameterization\x12\x0b\n\x03\x66_c\x18\x01 \x03(\x01\"\xad\x02\n\x1aSampleFuncParameterization\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\x0c\n\x04mass\x18\x02 \x01(\x01\x12\n\n\x02\x63\x66\x18\x03 \x01(\x01\x12\n\n\x02\x63r\x18\x04 \x01(\x01\x12\n\n\x02lf\x18\x05 \x01(\x01\x12\n\n\x02lr\x18\x06 \x01(\x01\x12\r\n\x05ratio\x18\x07 \x01(\x01\x12\x0b\n\x03tua\x18\x08 \x01(\x01\x12\n\n\x02Iz\x18\t \x01(\x01\x12\x1b\n\rperturb_value\x18\n \x01(\t:\x04None\x12\x44\n\rfeedback_func\x18\x0b \x03(\x0b\x32-.drive.common.control_v2.FuncParameterization\x12\x0f\n\x07\x66\x66_func\x18\x0c \x03(\x01\x12\x0e\n\x06\x62l_val\x18\r \x03(\x01\x12\x16\n\x0bsample_type\x18\x0e \x01(\x05:\x01\x30\"n\n\x1b\x43ontrolActionSamplingParams\x12O\n\x12sample_func_params\x18\x01 \x03(\x0b\x32\x33.drive.common.control_v2.SampleFuncParameterization')
)




_FUNCPARAMETERIZATION = _descriptor.Descriptor(
  name='FuncParameterization',
  full_name='drive.common.control_v2.FuncParameterization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_c', full_name='drive.common.control_v2.FuncParameterization.f_c', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=94,
)


_SAMPLEFUNCPARAMETERIZATION = _descriptor.Descriptor(
  name='SampleFuncParameterization',
  full_name='drive.common.control_v2.SampleFuncParameterization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='drive.common.control_v2.SampleFuncParameterization.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='drive.common.control_v2.SampleFuncParameterization.mass', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cf', full_name='drive.common.control_v2.SampleFuncParameterization.cf', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cr', full_name='drive.common.control_v2.SampleFuncParameterization.cr', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lf', full_name='drive.common.control_v2.SampleFuncParameterization.lf', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lr', full_name='drive.common.control_v2.SampleFuncParameterization.lr', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratio', full_name='drive.common.control_v2.SampleFuncParameterization.ratio', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tua', full_name='drive.common.control_v2.SampleFuncParameterization.tua', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Iz', full_name='drive.common.control_v2.SampleFuncParameterization.Iz', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perturb_value', full_name='drive.common.control_v2.SampleFuncParameterization.perturb_value', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("None").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedback_func', full_name='drive.common.control_v2.SampleFuncParameterization.feedback_func', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ff_func', full_name='drive.common.control_v2.SampleFuncParameterization.ff_func', index=11,
      number=12, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bl_val', full_name='drive.common.control_v2.SampleFuncParameterization.bl_val', index=12,
      number=13, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_type', full_name='drive.common.control_v2.SampleFuncParameterization.sample_type', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=398,
)


_CONTROLACTIONSAMPLINGPARAMS = _descriptor.Descriptor(
  name='ControlActionSamplingParams',
  full_name='drive.common.control_v2.ControlActionSamplingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_func_params', full_name='drive.common.control_v2.ControlActionSamplingParams.sample_func_params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=510,
)

_SAMPLEFUNCPARAMETERIZATION.fields_by_name['feedback_func'].message_type = _FUNCPARAMETERIZATION
_CONTROLACTIONSAMPLINGPARAMS.fields_by_name['sample_func_params'].message_type = _SAMPLEFUNCPARAMETERIZATION
DESCRIPTOR.message_types_by_name['FuncParameterization'] = _FUNCPARAMETERIZATION
DESCRIPTOR.message_types_by_name['SampleFuncParameterization'] = _SAMPLEFUNCPARAMETERIZATION
DESCRIPTOR.message_types_by_name['ControlActionSamplingParams'] = _CONTROLACTIONSAMPLINGPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuncParameterization = _reflection.GeneratedProtocolMessageType('FuncParameterization', (_message.Message,), dict(
  DESCRIPTOR = _FUNCPARAMETERIZATION,
  __module__ = 'control_v2.sample_action_pb2'
  # @@protoc_insertion_point(class_scope:drive.common.control_v2.FuncParameterization)
  ))
_sym_db.RegisterMessage(FuncParameterization)

SampleFuncParameterization = _reflection.GeneratedProtocolMessageType('SampleFuncParameterization', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEFUNCPARAMETERIZATION,
  __module__ = 'control_v2.sample_action_pb2'
  # @@protoc_insertion_point(class_scope:drive.common.control_v2.SampleFuncParameterization)
  ))
_sym_db.RegisterMessage(SampleFuncParameterization)

ControlActionSamplingParams = _reflection.GeneratedProtocolMessageType('ControlActionSamplingParams', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLACTIONSAMPLINGPARAMS,
  __module__ = 'control_v2.sample_action_pb2'
  # @@protoc_insertion_point(class_scope:drive.common.control_v2.ControlActionSamplingParams)
  ))
_sym_db.RegisterMessage(ControlActionSamplingParams)


# @@protoc_insertion_point(module_scope)

# With migration to Python3, Protobuf Python bindings
# ceased to accept `str` inputs for deseralization methods,
# instead requiring a `bytes` argument.
# However, we typically use ROS' std_msgs.String to persist
# Protobuf messages, and despite what the official documentation
# claims, with rospy3, `type(Std_msgs.Str.data) == str` and not `bytes`.
# To avoid the need to update every single Python application that
# deals with Protobuf [de]serialization with some backward compatibility
# glue code, we'll instead dynamically replace the parsing methods'
# implementations with thunks which also accept conventional `str` inputs,
# but convert them to the same raw `bytes` value before invoking
# the actual native bound methods.
if sys.version_info[0] >= 3:
    for cls in _sym_db._classes.values():
        for method_name in ('FromString',
                            'MergeFromString',
                            'ParseFromString'):
            method = getattr(cls, method_name)
            if not method:
                # Should not happen, but just in case
                continue

            # Using an ad hoc lambda so that upon
            # dynamic reflection people instantly
            # see the functor name and realize it's
            # something we did and not a good deed
            # from Protobuf (ha, if only...).
            def plusai_patched(self, s):
                if isinstance(s, str):
                    # Preserve the original byte sequence
                    # since it's serialized Protobuf and
                    # definitely do not want to modify it
                    # in any way.
                    s = bytes(map(ord, s))
                return method(self, s)

            setattr(cls, method_name, plusai_patched)

